all:
    children:
        manager:
            hosts:
                server:
                    ansible_connection: ssh
                    ansible_user: root
                    ansible_host: ovz4.j49321827.pqj7n.vps.myjino.ru
                    ansible_port: 49224
#        agent:
#            hosts:
#                agent-1:
#                    ansible_connection: ssh
#                    ansible_user: root
#                    ansible_host: 0.0.0.1
#                    ansible_port: 22